### PR TITLE
Use manifest on Windows

### LINKED ISSUE #26: Windows native-image error for large classpath
**Describe the bug**

Windows native image builds fail when there are a large number of JARs in the classpath.
It looks like previously a single manifest.jar was used to avoid this issue, but this was removed for Windows in #9

**To Reproduce** Steps to reproduce the behavior:

1. Create a new SBT project with a large number (~50) of dependencies
2. Run `sbt nativeImage`

**Expected behavior**
`native-image` is invoked to create the binary

**Screenshots**
Instead, the command fails due to the length of the command:
```
[info] C:\Users\runneradmin\AppData\Local\Coursier\cache\jvm\graalvm-java11@20.2.0\bin\native-image.cmd -cp [long class path here] com.example.MyClass D:\a\my-project\my-project\target\native-image\my-project
 The command line is too long.
[error] native-image command failed with exit code '1'
[error] (my-project / nativeImage) native-image command failed with exit code '1'
```

**Installation:**

- Operating system: Windows
- Version: v0.3.0

**Additional context**
I've been able to work around this for now by pre-assembling a fat jar with sbt-assembly, and then overriding the classpath with the result:
```
fullClasspath in Compile := Seq(Attributed(assembly.value)(AttributeMap.empty)),
```

**Search terms**

Windows classpath

### PR DESCRIPTION
**Pull request by DaniRey**
This change fixes #26 Windows native-image error for large classpath, by using the manifest on Windows.
Absolute paths in manifests are only supported with some JDKs on Windows, therefore I used relative paths.
Relative paths may not be URL encoded, otherwise an absolute path is generated

### CODE REVIEW

**Comment by olafurpg** [comment]
Thank you for this contribution! I'm glad to see this finally get fixed. It's always been unsatisfying that we didn't use manifest jars on Windows. I'm happy to merge this PR once the Windows CI is green. I just noticed that Scalafmt and Scalafix haven't been added to the build. I will add them after merging this PR so don't worry about the unrelated formatting changes, they will get fixed later.

**Comment by DaniRey** [comment]
Unfortunately the Windows build now fails with ` [error] java.lang.IllegalArgumentException: 'other' has different root`

I assume this is caused by the image being built in D: while some of its dependencies are in C:
This cannot work with relative paths. 

In my experience people no longer use multiple drives on Windows. Therefore chaining the configuration of the windows-latest CI image/build might be an option. Maybe a config switch to change between manifest and classpath would make sense, to avoid breaking anyone's workflow in a way they cannot recover from.

**Comment by olafurpg** [comment]
I'm not very familiar with Windows so this is a guess. It looks like the jars from the dependency classpath are living in a different drive from the manifest jar. It could be that the dependency jar is on a different drive because coursier downloads dependencies to the system cache directory. If that's true, then I suspect this will be a common issue for sbt-native-image users who want to build/upload native-image binaries from GitHub Actions.

>  Maybe a config switch to change between manifest and classpath would make sense, to avoid breaking anyone's workflow in a way they cannot recover from.

I don't think a config option will solve the problem here because if the application needs a manifest jar (because the classpath is too large) then it will fail with a "argument list too long" error.

One possible workaround is to copy the dependency jar into the same target directory as the manifest jar. That would ensure the jars are always on the same drive. What do you think?

**Comment by DaniRey** [comment]
> One possible workaround is to copy the dependency jar into the same target directory as the manifest jar. That would ensure the jars are always on the same drive. 
That sounds like a good solution. We could even check if it is on the same drive and only copy dependencies which reside on a different drive.

Would you call an according method from `addTrailingSlashToDirectories` or would you add this as a first call to `.map` in the following snippet?

```
  private def createManifestJar(manifestJar: File, cp: Seq[File]): Unit = {
    // Add trailing slash to directories so that manifest dir entries work
    val classpathStr =
      cp.map(addTrailingSlashToDirectories(manifestJar)).mkString(" ")
```

i.e.

```  private def createManifestJar(manifestJar: File, cp: Seq[File]): Unit = {
    // Add trailing slash to directories so that manifest dir entries work
    val classpathStr =
      cp
      .map(assertSameRootAs(manifestJar))
      .map(addTrailingSlashToDirectories(manifestJar))
      .mkString(" ")
```

**Comment by olafurpg** [comment]
We can add a try/catch to the `.relativize` method that falls back to copying the dependency jar into the same drive as the manifest jar and tries again

File: plugin/src/main/scala/sbtnativeimage/NativeImagePlugin.scala [hunk 1]
```diff
@@ -311,7 +311,20 @@ object NativeImagePlugin extends AutoPlugin {
...
+      try {
+        manifestPath.relativize(dependencyPath).toString
+      } catch {
+        //java.lang.IllegalArgumentException: 'other' has different root
+        //this happens if the dependency jar resides on a different drive then the manifest, i.e. C:\Coursier\Cache and D:\myapp\target
+        //copy dependency next to manifest as fallback
+        case _: IllegalArgumentException =>
+          import java.nio.file.Files
+          import java.nio.file.StandardCopyOption
+          Files.copy(dependencyPath, manifestPath.resolve(path.getName), StandardCopyOption.REPLACE_EXISTING)
```
Comment (olafurpg) [inline plugin/src/main/scala/sbtnativeimage/NativeImagePlugin.scala:325]: Should this be “resolveSibling”?

Comment (olafurpg) [reply plugin/src/main/scala/sbtnativeimage/NativeImagePlugin.scala:325]: Nevermind

**Review by olafurpg — APPROVED** [review]
LGTM will merge once ci is green :)

**Comment by olafurpg** [comment]
Just published https://github.com/scalameta/sbt-native-image/pull/31 it may take a few hours until it's available on Maven Central

**Comment by DaniRey** [comment]
Great, thank you Ólafur
